spring:
  application:
    name: course-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:course-service;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:input.sql
  jpa:
    defer-datasource-initialization: true

server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/