server:
  port: 8888

spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dgarciadani/config-repo-checkpoint-backend.git
