server:
  port: 8080

spring:
  application:
    name: movie-service
  config:
    import: optional:configserver:http://localhost:8888


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver