spring:
  application:
    name: image-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: default


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


image:
  url: nofuncino/serveronfig/
