server:
  port: 8080
  servlet:
    context-path: /catalog

spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      port: 27018
      database: catalogFP
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/